name: Build

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Add> Node/NPM
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: npm

      - name: <Install> NPM
        run: npm ci

      - name: <Build> Blog
        run: npm run build

      - name: <Artifact> Blog
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: build

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-22.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: <Download> Application
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

